package cu.suitetecsa.kotlibsuitetecsa.utils

enum class Operation {
    LOGIN,
    LOAD_USER_INFO,
    RECHARGE,
    TRANSFER,
    CHANGE_PASSWORD,
    CHANGE_EMAIL_PASSWORD,
    CONNECTIONS,
    CONNECTIONS_SUMMARY,
    CONNECTIONS_LIST,
    RECHARGES,
    RECHARGES_SUMMARY,
    RECHARGES_LIST,
    TRANSFERS,
    TRANSFERS_SUMMARY,
    TRANSFERS_LIST,
    QUOTES_FUNDS,
    QUOTES_FUNDS_SUMMARY,
    QUOTES_FUNDS_LIST
}