package cu.suitetecsa.sdk.nauta.utils

enum class Action {
    LOGIN,
    LOAD_USER_INFORMATION,
    RECHARGE,
    TRANSFER,
    NAUTA_HOGAR_PAID,
    CHANGE_PASSWORD,
    CHANGE_EMAIL_PASSWORD,
    GET_CONNECTIONS,
    GET_RECHARGES,
    GET_TRANSFERS,
    GET_QUOTES_PAID,
    LOGOUT,
    CHECK_CONNECTION
}