package cu.suitetecsa.kotlibsuitetecsa

enum class Attribute {
    USER_NAME,
    ACCOUNT_TYPE,
    SERVICE_TYPE,
    CREDIT,
    TIME,
    MAIL_ACCOUNT,
    OFFER,
    MONTHLY_FEE,
    DOWNLOAD_SPEEDS,
    UPLOAD_SPEEDS,
    PHONE,
    LINK_IDENTIFIERS,
    LINK_STATUS,
    ACTIVATION_DATE,
    BLOCKING_DATE,
    DATE_OF_ELIMINATION,
    BLOCKING_DATE_HOME,
    DATE_OF_ELIMINATION_HOME,
    QUOTA_FUND,
    VOUCHER,
    DEBT
}
