name: Run Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.2.0
      
    - name: set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test
